# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ired
                                 A QGIS plugin
 Integración de Recursos Energéticos Distribuidos
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-11-13
        copyright            : (C) 2020 by EPERLab
        email                : eperlab.eie@ucr.ac.cr
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ired class from file ired.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .ired import ired
    return ired(iface)
